### PR TITLE
Halve output goo after summing instead of summing the halves

### PR DESCRIPTION
**Pull request by hypnoshock**
# What

We were summing up halves of the inputs which meant we lost all fractional parts due to working with integers so `(5/2) + (5/2) = 4`. By summing and then halving we get the expected output `(5 + 5) / 2 = 5`

# Testing

You can make a building that takes two inputs of 5 goo which should yield an output item with 5.

```

---
kind: BuildingKind
spec:
  category: factory
  name: Goo Halver
  description: Halve red goo for a laugh
  model: 01-09
  color: 4
  contract:
    file: ./basic-factory.sol
  plugin:
    file: ./basic-factory.js
  materials:
  - name: Red Goo
    quantity: 10
  - name: Green Goo
    quantity: 10
  - name: Blue Goo
    quantity: 10
  inputs:
  - name: Red Goo
    quantity: 5
  - name: Red Goo
    quantity: 5
  outputs:
  - name: Red Fiver
    quantity: 1

---
kind: Item
spec:
  name: Red Fiver
  icon: 31-16
  goo:
    red: 5
    green: 0
    blue: 0
  stackable: false

```

resolves: #695

### CODE REVIEW

**Review by chrisfarms — APPROVED** [review]
LGTM ... this does feel like it deserves a test case tho since it'll be a subtle regression

**Review by 5p0rt5BEArD — APPROVED** [review]
tested

**Comment by 5p0rt5BEArD** [comment]
@hypnoshock will leave up to you to either merge or add a test first

**Review by ldunnplaymint — APPROVED** [review]

**Comment by hypnoshock** [comment]
> @hypnoshock will leave up to you to either merge or add a test first

Test added. @ldunnplaymint feel free to merge if unit test passes as expected

**Review by ldunnplaymint — APPROVED** [review]

**Pull request merged**
