### PR TITLE
Croissant Map Iterations - Multiple changes

### PR DESCRIPTION
**Pull request by PlaymintPaul**

### CODE REVIEW

**Comment by 5p0rt5BEArD** [comment]
Addresses issue #1120

**Comment by 5p0rt5BEArD** [comment]
Some points that I could just do myself if you agree with them:

- I included adding a building to make use of id card and letter in the issue
- This could be the cupis
- The apex needs moving ;)

image


image

**Comment by PlaymintPaul** [comment]
>     * The apex needs moving ;)

Eh?! Mine is much closer to the image than your proposed one :)

**Review by 5p0rt5BEArD — APPROVED** [review]
We played as a team and all looks good

**Pull request merged**
