### PR TITLE
Quest buildings

### PR DESCRIPTION
**Pull request by PlaymintPaul**
Work done to get quest buildings into the game (as much as I can without the quests)

### CODE REVIEW

**Comment by ldunnplaymint** [comment]
Not sure the greyed out sentence makes sense
Screenshot 2023-10-10 at 17 28 50

**Comment by ldunnplaymint** [comment]
The tower of knowledge doesn't do anything when I select the docs or create a building buttons. At least, it isn't telling me why they aren't doing anything/potentially active when they shouldn't be.

**Comment by ldunnplaymint** [comment]
An error fires if the user selects the Registry Office without their unit selected. Probs best to action to fix it #701  

```client.js:1 plugin did not return an expected response object: TypeError: cannot read property 'bags' of undefined
    at update (__plugin__:17)
    at <anonymous> (eval.js:4)
    at <anonymous> (eval.js:2)
    at <eval> (eval.js:3)
Host: QuickJSUnwrapError
    at QuickJSContext.unwrapResult (webpack-internal:///../node_modules/quickjs-emscripten/dist/context.js:649:35)
    at eval (webpack-internal:///../core/src/plugins.ts:500:48)
    at async Promise.all (index 0)```

**Comment by PlaymintPaul** [comment]
> The tower of knowledge doesn't do anything when I select the docs or create a building buttons. At least, it isn't telling me why they aren't doing anything/potentially active when they shouldn't be.

Yeah I don't know how to do that, or if we even have the right pages to point to.  It's a placeholder button

**Comment by PlaymintPaul** [comment]
> An error fires if the user selects the Registry Office without their unit selected. Probs best to action to fix it #701
> 
> ```
>     at update (__plugin__:17)
>     at <anonymous> (eval.js:4)
>     at <anonymous> (eval.js:2)
>     at <eval> (eval.js:3)
> Host: QuickJSUnwrapError
>     at QuickJSContext.unwrapResult (webpack-internal:///../node_modules/quickjs-emscripten/dist/context.js:649:35)
>     at eval (webpack-internal:///../core/src/plugins.ts:500:48)
>     at async Promise.all (index 0)```
> ```

I wondered if that check was still needed. I'll put it back

**Pull request merged**
