### PR TITLE
Zones list paint job part one

### PR DESCRIPTION
**Pull request by chrisfarms**
## what

bringing the zone list page inline with design we want ... not implemented any of the filter controls, but this is the basics and should be working...

Screenshot 2024-05-10 at 12 39 56

## why

* resolves: #1203 
* resolves: #1387

## divergance from mock ups

* using very simple toggle buttons for "ALL | ACTIVE | YOURS" instead of the complex filter stuff for now, since we don't have enough data for interesting complex filters
* there is no "sort" options ... things are always sorted by "activity" ... where "activity" is either the number of active units or the time of the last active unit
* filtering by "ACTIVE" means "show me only zones with more than 1 tile that someone has entered at some point before, then sort them by "activity" as above

### CODE REVIEW

**Comment by ldunnplaymint** [comment]
If I mint a zone, I don't see it immediately as no one is active. I think the filter should switch to "Yours" if you mint a zone.

**Comment by chrisfarms** [comment]
> If I mint a zone, I don't see it immediately as no one is active. I think the filter should switch to "Yours" if you mint a zone.

👍  ... pushed change that does this

I have also made it so that "ACTIVE" always shows you your own zones even if they are not technically active, as this seems less surprizing

**Comment by ldunnplaymint** [comment]
The mint success text is wrong, always was but now way more obvious
Screenshot 2024-05-10 at 13 25 25

**Comment by chrisfarms** [comment]
> The mint success text is wrong...

what do you want it to say?

**Comment by ldunnplaymint** [comment]
> > The mint success text is wrong...
> 
> what do you want it to say?

"Mint successful! Please fing your Zone in the list below!"

**Comment by ldunnplaymint** [comment]
The bottom playmint button does nothing

**Comment by ldunnplaymint** [comment]
> > The bottom playmint button does nothing
> 
> it's not a button, just a logo 🤷

It looks like a button 🤔

**Review by ldunnplaymint — APPROVED** [review]

**Pull request merged**
