### PR TITLE
Zoner Controls & Information

### PR DESCRIPTION
**Pull request by Steedie**
## What
1. Adds "Owner Controls" to the "Settings" panel (`nav-panel.tsx`)
image

2. Adds an "Owner Information"/welcome section for zone owners
image

3. Changes the player icon to a cog icon
image

4. Removes the unclickable "WALLET" button when you're not connected
### Before
image
### After
image

## Why
1. Allows the zone owner to rename their "Island", and change it's description.
2. Helps zoners to get started.
3. The `nav-panel` is no longer just player-related.
4. Previously, the "WALLET" button was always visible, even when you weren't connected to a wallet.

## Resolves
- #1210 
- #1212

### CODE REVIEW

**Review by ldunnplaymint — APPROVED** [review]

**Comment by Steedie** [comment]
> I think it's weird that you cannot access the owner information after you have spawned a unit. I think I should be able to access that info at any time. Other than that, looks good!

I see what you mean...  gonna look into this some more.

**Comment by chrisfarms** [comment]
> I think it's weird that you cannot access the owner information after you have spawned a unit. I think I should be able to access that info at any time. Other than that, looks good!

yeah maybe show it unless there are more than 1 Tiles .... that would imply they have worked out how to deploy and no longer need the prompt

**Comment by ldunnplaymint** [comment]
Errors while building:```  ⨯ ./src/components/organisms/onboarding/index.tsx
 Error:
   x the name `isZoneOwner` is defined multiple times
     ,-[/Users/lewisdunn/Repos/ds/frontend/src/components/organisms/onboarding/index.tsx:37:1]
  37 | }: OnboardingProps) => {
  38 |     const [isSpawningMobileUnit, setIsSpawningMobileUnit] = useState<boolean>(false);
  39 |
  40 |     const isZoneOwner = player && zone.owner && zone.owner.addr === player.addr;
     :           ^^^^^|^^^^^
     :                `-- previous definition of `isZoneOwner` here

  88 |     const { wallet } = useWallet();
  89 |     const address = player?.addr || wallet?.address || '';
  90 |     const isZoneOwner = address === zone?.owner?.addr;
     :           ^^^^^|^^^^^
     :                `-- `isZoneOwner` redefined here
```

**Comment by Steedie** [comment]
## Updates
- continues to show "Owner Information" until at least another tile has been built ([28bcae9](https://github.com/playmint/ds/pull/1272/commits/28bcae9f8b680b5cd7a637ad4a72b5daccca1f05))
- changes between wallet/cog icon: wallet if the button says "CONNECT", cog if you've already connected ([deb2876](https://github.com/playmint/ds/pull/1272/commits/deb28765c4f2d187c15ad7a6b2ea37c9cc3b6c90))
- only shows "WALLET" **button** if you're connected to a wallet ([e93b293](https://github.com/playmint/ds/pull/1272/commits/e93b293c581927715472911ca1265799b5c610b1))
  - the "WALLET" button was previously always showing even when unclickable

## Notes
I had to add state.setData back to the description naming rule otherwise changing the description wasn't working:
```solidity
state.setData(entity, "description", bytes32(bytes(desc)));
state.annotate(entity, "description", desc);
```
**Will this break anything?** ([20144d5](https://github.com/playmint/ds/pull/1272/commits/20144d51f63cf2138f13c28c032927d199fcae5b))

**Review by ldunnplaymint — APPROVED** [review]

**Review by ldunnplaymint — APPROVED** [review]

**Pull request merged**
