### PR TITLE
Replaced buildings with door models for Labyrinth

### PR DESCRIPTION
**Pull request by JackPlaymint**
Swaps out the factory models with door models for Labyrinth game.
Also added logic to swap open/closed states in each door's js.

### CODE REVIEW

**Comment by 5p0rt5BEArD** [comment]
Looks great - just about to do a test run

We don't a rotation to match a horizontal connection - nevermind!
Screenshot at Mar 13 13-01-40

**Comment by ldunnplaymint** [comment]
I was just writing my comment but Iain beat me to it!

**Comment by 5p0rt5BEArD** [comment]
@ldunnplaymint I had trouble `ds applying` the labyrinth map with the lastest cli but was fixed if I built the cli myself
would be good to check latest cli is working with rotated buildings

**Comment by 5p0rt5BEArD** [comment]
> I was just writing my comment but Iain beat me to it!

ha sorry

I'll leave you to it - was keen to get in here to make some presentation footage

**Comment by ldunnplaymint** [comment]
I ran `npm install @playmint/ds-cli -g` to update the cli and then `ds apply -R -f ./contracts/src/maps/labyrinth` to apply the map...
Worked for me!

**Review by ldunnplaymint — APPROVED** [review]

**Pull request merged**
