### PR TITLE
ds-cli: basic cli skeleton

### PR DESCRIPTION
**Pull request by chrisfarms**
initial project layout and command structure for a downsteam cli 

this doesn't do anything very interesting yet, but gets all the bits in roughly the right shape ready to work on the building deployment bits.

I chose the [yargs](http://yargs.js.org/) lib to help with the structuring mostly because it was very easy to get going with, but it isn't great at typesafty (or at least I haven't managed to convince it to be yet) - so it's a little fast and loose with types.

the general command structure is:

```
ds [noun] [verb] [params]
```

I've made a couple of example commands to test we can read from the graphql...

```
ds items list
ds items search goo
ds items show <id>
```

... and dispatch actions

```
ds actions list
ds actions dispatch SPAWN_MOBILE_UNIT <id>
```

You can point the cli at different deployments by using the `--network` (or `-n`) option:

```
ds --network devnet items list
```

To see the available network endpoints use `ds networks`

```
ds networks list
```

Actions that require a signature/session will prompt to signin with a walletconnect QR code rendered in the terminal.

Outputs are roughly rendered using `console.table` for now .... or you can switch to JSON with the `-o json` option:

```
ds -o json items list
```

... I have tested publishing the package, but we will need to automate it ... created #485 to track this ... for now it can be published by hand via `npm run build && npm publish`

### CODE REVIEW

**Comment by ldunnplaymint** [comment]
I hit this when trying to do the tile deploy on windows:
```SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.handler (C:\Users\lewis\AppData\Roaming\npm\node_modules@playmint\ds-cli\dist\ds.js:88158:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)```

**Comment by chrisfarms** [comment]
is there any more output? looks like that has been truncated so cant see the error

**Comment by chrisfarms** [comment]
@ldunnplaymint what command shell are you using on windows? ... you might have to use `"` in `cmd` but `'` should be ok in powershell or git-bash

**Comment by ldunnplaymint** [comment]
My bad, looks good

**Review by ldunnplaymint — APPROVED** [review]

**Pull request merged**
