### PR TITLE
CSS restyle

### PR DESCRIPTION
**Pull request by hypnoshock**
# What

Overhaul on CSS styling to bring the game visual closer to Jonny's interim/halfway design

image
image
image
image

Also along the way I fix the scrolling issue in the combat panel where a scrollbar appeared for the whole model instead of the area where the participants are shown

# Todo

- [x] Inventory and item slots
- [x] Selected seeker panel
  - [x] Replace red shield icon with the orange backed seeker icon
  - [x] Seeker name text to match design
- [ ] Grey headers on panels to match the style as seen on quest panel
- [ ] Modal close buttons look a bit weird (need Jonny's input)
- [ ] Incorporate a proper design for the combat panel (Need Jonny's input)
- [x] There are plenty of white pngs which need turning orange
  - [x] Sword and shield on participants in combat panel
  - [x] Replace the blue backed combat icon. At least turn the background orange?
  - [x] Arrow in crafting panel

### CODE REVIEW

**Comment by ldunnplaymint** [comment]
I think the slot backgrounds are to dark in contrast to the white panels, makes it hard to see the icon/text in an empty slot
Screenshot 2023-10-23 at 09 49 44

**Comment by ldunnplaymint** [comment]
The unit icon is off of the unit panel and the cocktail item plugin seems incorrectly formatted. 

Screenshot 2023-10-23 at 09 58 59

**Comment by ldunnplaymint** [comment]
Is it possible to swap the shield Unit icon for the orange hexagon icon in the unit panel?

**Comment by ldunnplaymint** [comment]
### Stuff for this PR
- The "This item goes there" highlight when trying to put a required item into a well is too subtle
- Item wells are too dark and the faded item icons/text are too knocked back
- Unlit intent buttons are too hard to read. The Light orange on white isn't legible.

### Other stuff
- We should change the unit panel icon to the orange hex icon, shield is SO yesterday
- The Quest tabbing (Is that what you call it?) is a big clumsy but it works for now

**Comment by hypnoshock** [comment]
> I think the slot backgrounds are to dark in contrast to the white panels, makes it hard to see the icon/text in an empty slot Screenshot 2023-10-23 at 09 49 44

image

Now with a less contrasting style

**Comment by ldunnplaymint** [comment]
Screenshot 2023-10-24 at 09 17 09
Unit icon is wrong on combat modal as well, for when you do the unit panel

**Review by ldunnplaymint — APPROVED** [review]

**Pull request merged**
