### PR TITLE
Hexcraft ZoneKind "Reset World"

### PR DESCRIPTION
**Pull request by Steedie**
## What
- Adds a "Reset World" button to the Hexcraft HQ building

## How
- List of all building kind ids and another of the tile they should be on is is created in the Hexcraft Zone.sol constructor, then in a for loop it calls the `DEV_SPAWN_BUILDING` action and replaces all buildings in the map.

## Notes
~~The functionality errors I was having are now resolved, but this PR is currently a draft because I need to tidy it all up and rearrange the code and files.~~

## Resolves

- fixes: #1340 
- fixes: #970

### CODE REVIEW

**Review by ldunnplaymint — APPROVED** [review]

**Review by ldunnplaymint — APPROVED** [review]

**Comment by 5p0rt5BEArD** [comment]
> The functionality errors I was having are not resolved, but this PR is currently a draft because I need to tidy it all up and rearrange the code and files.

are there still no errors?

**Comment by Steedie** [comment]
> > The functionality errors I was having are not resolved, but this PR is currently a draft because I need to tidy it all up and rearrange the code and files.
> 
> are there still no errors?

Ah yep, forgot to remove the note. No errors now and I finished tidying it up.

**Review by JackPlaymint — APPROVED** [review]
lgtm!

**Review by 5p0rt5BEArD — CHANGES_REQUESTED** [review]
Can you move the zone files to the root folder please :)

**Review by ldunnplaymint — APPROVED** [review]

**Comment by Steedie** [comment]
> Can you move the zone files to the root folder please :)

Tried doing this but after I moved all the zone files to the root I was getting this error:
image

Though all necessary paths I changed appeared to be correct.

[In the latest commit](https://github.com/playmint/ds/pull/1390/commits/f22a197382836cd2ae921f1c983e65ab4fe66f3b), I moved just the Zone.yaml file to the map root and left the Zone solidity files in the contracts folder so it's working now.

**Review by 5p0rt5BEArD — APPROVED** [review]
The zone yaml in the route is probably the main thing

**Pull request merged**
