### PR TITLE
one-click construct

### PR DESCRIPTION
**Pull request by chrisfarms**
## what

* makes "construct" a one-click action that works out how to pay for the materials from what is in the unit's inventory
* closes: #344 by making the situation impossible
* resolves the bug where the construct control would disapear midday through your attempt to construct if you used up the last material
* shows the description + cost in words for the selected thing

## note

this means there is no UI to contribute to a "building site"... but since this "unknowable partial construction" problem has come up a few times and causes confusion, this was agreed with paul as a quick fix for the issue.

it also feels less tedious to make a building this way so maybe it's preferable long term anyway 🤷 

Screenshot 2023-09-01 at 07 19 51

### CODE REVIEW

**Comment by ldunnplaymint** [comment]
This feels abit more confusing to me. I get that the buildings go into the unconstrucable pile when I cannot make them but 1) It is now loads of effort to find out what buildings need to be constructed and 2) Having the unconstrucable pile also contain the "1337 br1c|<z" buildings makes it quite unwieldy. I also imagine that list will just be horrendous when other people start deploying.

**Comment by chrisfarms** [comment]
I haven't changed the behaviour of the unconstructable pile here?

**Comment by ldunnplaymint** [comment]
I mean that when I cannot afford to construct a building, it gets added to that pile. Before, it was basically the "I can ignore this" pile in my head, now I have to sift through it if I want to remember what a construction costs.

**Comment by chrisfarms** [comment]
well yes ... it was broken before and should not have been showing you something you cannot build 😅 

we have not got a good solution for this selection yet... the previously methods have not worked and this isn't great either ... but the main things we are trying to archive are:

* Your own deployed buildings are always at the top
* It groups things to help you a bit
* try not to overwealm someone with a list of crap they can't build (unless they opt in)

Your desire seems to be "I want to find out what buildings I might be able to make in the future" ... which is a totally legit desire, and something that we should have a solution for ... but not something this selection list is ever going to be good for, needs a proper library of all the things you can filter and search ... not a picker

**Review by ldunnplaymint — APPROVED** [review]

**Pull request merged**
